# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebasDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebasDemo
	pod 'Firebase/Core'

  target 'FirebasDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebasDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
